<?php
/**
 * @var string $title
 * @var string $content
 *
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlentities($title); ?></title>
    <link rel="stylesheet" href="/css/lib/bulma/bulma.min.css">
    <link rel="stylesheet" href="/css/main.css">
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body>

    <?php echo $content; ?>

</body>
</html>
